<?php
itron::$locale = array_merge(itron::$locale,array(
    "_installer_newword_title" => "Newword",
    "_installer_newword_type" => "_types_blog",
    "_installer_newword_category" => "_categories_contentmanagementsystems",
    "_installer_newword_description" => "WordPress is an open source blog application. WordPress forked from b2/cafelog in 2003, and WordPress Mu multiple website functionality has been integrated since 2010. Today WordPress is the most used blog application powering millions of blogs and being used by tens of millions of people every day.",
    "_installer_newword_authordescription" => "WordPress является персональной платформой для публикаций и блогов приложений с акцентом на эстетику, веб-стандарты и удобство использования.<br><br>Особенности:<ul><li>Дополнительные страницы позволяют управлять обычным контентом легко, таким как например страница &quot;Обо мне&quot;.<li>Большая система тем позволяет создавать как простейшие блоги так и сложные веб-журналы с легкостью.<li>Изменения, внесенные в шаблоны и записи, немедленно отражаются на вашем сайте, без необходимости восстановления статических страниц, и все сгенерированные HTML полностью совместимы со стандартами W3C.<li>Trackback и Pingback стандарты полностью поддерживается.<li>Посетители могут оставлять комментарии на записи в блогах и комментирование можно отключить в любом конкретном сообщении.<li>Защита от спама в комментариях исключает нежелательных пользователей с вашего блога.<li>Регистрация пользователя позволяет посетителям регистрировать и поддерживать профили, а так же оставлять комментарии в блоге, если они включены.<li>Защищенные паролем сообщения позволяют устанавливать пароли на отдельные сообщения, чтобы скрыть их от общественности.* Полный XML-RPC интерфейс позволяет расширить WordPress и использовать приложения, предназначенные для других платформ, например, таких как Zempt.<li>Функция группы пользователей позволяет модерировать до 10 уровней доступа, имеющие различные (и настраиваемые) льготы по публикации, редактированию и прочие опционы.<li>Букмарклеты позволяют легко публиковать ваши сообщения или добавить ссылки на ваш  блог.</ul>",
    "_installer_newword_multisite_yes" => "Да, включить мультисайтовость для использования нескольких сайтов либо субдоменах",
    "_installer_newword_multisite_no" => "Нет, не включать. Multi-сайт может быть включен позже в WordPress. (Рекомендуется)",
    "_installer_newword_limitloginattempts_yes" => "Да, ограничить количество неудачных попыток входа в систему для повышения безопасности. (Рекомендуется)",
    "_installer_newword_limitloginattempts_no" => "Нет, не ограничивать количество неудачных попыток входа.",
));


//_installer_newwordnewword_title=WordPress
//_installer_newword_type=_types_blog
//_installer_newword_category=_categories_contentmanagementsystems
//_installer_newword_description=WordPress is an open source blog application. WordPress forked from b2/cafelog in 2003, and WordPress Mu multiple website functionality has been integrated since 2010. Today WordPress is the most used blog application powering millions of blogs and being used by tens of millions of people every day.
//_installer_newword_authordescription=WordPress is a personal publishing platform and blogging application with a focus on aesthetics, web standards, and usability.<br><br>Features:<ul><li>Additional pages allow you to manage non-blog content easily, so for example you could have a static "About Me" page.<li>A full theme system enables designing everything from the simplest blog to the most complicated webzine a piece of cake.<li>Changes made to templates and entries are reflected immediately on your site, with no need for regenerating static pages, and all generated HTML is fully compliant with W3C standards.<li>Trackback and Pingback standards fully supported.<li>Visitors can post comments on your blog entries, and commenting can be disabled on a per-post basis.<li>Spam protection eliminates comment spam from your blog.<li>User registration enables visitors to register and maintain profiles and leave authenticated comments on your blog, if enabled.<li>Password Protected Posts enables you to give passwords to individual posts to hide them from the public.<li>A full XML-RPC interface enables you to extend WordPress and use clients designed for other platforms like Zempt.<li>User groups enables up to 10 levels of users, with different levels having different (and configurable) privileges with regard to publishing, editing, options, and other users.<li>Bookmarklets make it easy to publish to your blog or add links to your blogroll with a minimum of effort.<li>Ping-O-Matic is supported, which means maximum exposure for your blog to search engines.</ul>
//_installer_newword_multisite_yes=Yes, enable multi-site support for sub-directories of the selected install location.
//_installer_newword_multisite_no=No, do not enable. Multi-site can be enabled later within WordPress. (Recommended)
//_installer_newword_limitloginattempts_yes=Yes, limit failed login attempts for increased security. (Recommended)
//_installer_newword_limitloginattempts_no=No, do not limit failed login attempts.